title: Margaret Capetz (she/her)
logo: linkedinpfp.png
author:
  name: Margaret Capetz
  email: mcapetz17@g.ucla.edu
# description: [Linkedin](https://github.com/mcapetz)
show_downloads: false
theme: jekyll-theme-minimal
social_links:
   - { platform: github,         user_url: "https://github.com/mcapetz" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/margaret-capetz/" }
